name: Docker CI Pipeline
run-name: ${{ github.actor }} is running out Docker CI Pipeline 🚀
on: [push]
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
       - name: Clone the code
         uses: actions/checkout@v4

       - name: Docker Login
         uses: docker/login-action@v3.4.0
         with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

       - name: Docker Build
         run: docker build -t ${{ secrets.DOCKER_USERNAME }}/helloworld-python:latest .

       - name: Docker Push
         run: docker push ${{ secrets.DOCKER_USERNAME }}/helloworld-python:latest

        
